version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tvtracksync
      MONGO_INITDB_ROOT_PASSWORD: tvtracksync
